name : CI 
on : 
    push :
      branches : [ main, develop]
    pull_request :
        branches : [ main, develop]

jobs :
  build :
    runs-on : ubuntu-latest

    steps :
    - uses : actions/checkout@v6
    - name : Set up Node.js
      uses : actions/setup-node@v6
    - run : npm ci
    - run : npm run lint
    - run : npm run test